### ISSUE TITLE
CRITICAL:root:Unable to read project configuration: error connecting to the database

### ISSUE THREAD

**Issue by marcfreir** [ROBelgium/MSNoise#216] opened 2021-03-08 11:07 UTC
Hi!

I'm using a Windows Machine. I got an error while I was testing the command ```msnoise test```:

```
(base) C:\Users\marcf>msnoise test
CRITICAL:root:Unable to read project configuration: error connecting to the database:
(pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '127.0.01' ([Errno 11001] getaddrinfo failed)")
(Background on this error at: http://sqlalche.me/e/13/e3q8)
```

I followed all the steps. MySQL is running fine. I created the DB and the user 'msnoise' with the password 'msnoise'.

Can someone help me?

**Comment by ThomasLecocq** [comment] 2021-03-09 08:50
euh, for normal tests the MySQL database shouldn't be tested at all.. Can you reproduce this in an empty folder ?

**Comment by marcfreir** [comment] 2021-03-10 23:50
> euh, for normal tests the MySQL database shouldn't be tested at all.. Can you reproduce this in an empty folder ?

Sorry! I'm a newbie. I just followed the steps. I opened the Anaconda terminal and typed the commands. I did a clean installation and checked all packages. I tried again in an empty folder and I got the same error. I was using MySQL so I uninstalled and now I using SQLite. Same error... I read the documentation (http://sqlalche.me/e/13/e3q8) but didn't help at all.

**Comment by asyates** [comment] 2021-03-19 18:00
When you say were using MySQL, and now SQLite, what do you mean? Do you mean after running msnoise db init? For running the 'msnoise test' you shouldn't need to indicate whether you are intending to use MySQL or SQLite. Can run immediately after installation of msnoise.

**Comment by marcfreir** [comment] 2021-03-20 14:54
> When you say were using MySQL, and now SQLite, what do you mean? Do you mean after running msnoise db init? For running the 'msnoise test' you shouldn't need to indicate whether you are intending to use MySQL or SQLite. Can run immediately after installation of msnoise.

Thanks for the answer! I just ran ```msnoise test``` and got the error. I already tried  ```msnoise db init``` but I got the same error.
The error I got for both commands ```msnoise test``` &  ```msnoise db init``` I ran each separately:
```CRITICAL:root:Unable to read project configuration: error connecting to the database:
(pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '127.0.01' ([Errno 11001] getaddrinfo failed)")
(Background on this error at: http://sqlalche.me/e/13/e3q8)```

**Comment by asyates** [comment] 2021-03-22 09:42
Not obvious to me what the problem is, but maybe you could try installing msnoise within a new conda environment instead?

I recently made a demo for a workshop with some installation instructions for doing just this (link below). Might be of use to you. Note, I am installing the master version in this, whereas you might prefer to just install the latest release (i.e. pip install msnoise). 

https://drive.google.com/drive/folders/1vQJ9s6C9tAZrEle8zm78G6sfIfukH5Ap?usp=sharing

**Comment by marcfreir** [comment] 2021-06-17 01:07
> Not obvious to me what the problem is, but maybe you could try installing msnoise within a new conda environment instead?
> 
> I recently made a demo for a workshop with some installation instructions for doing just this (link below). Might be of use to you. Note, I am installing the master version in this, whereas you might prefer to just install the latest release (i.e. pip install msnoise).
> 
> https://drive.google.com/drive/folders/1vQJ9s6C9tAZrEle8zm78G6sfIfukH5Ap?usp=sharing

My apologies for the late reply. I had some personal problems... I will try again. Thanks for the support!

**Comment by ThomasLecocq** [comment] 2021-10-18 08:13
closing this issue since it's been a long time without changes, feel free to comment again if it's not solved

**Closed by ThomasLecocq** 2021-10-18 08:13 UTC
